// lib/config/bitola_config.dart
class BitolaConfig {
  static const Map<String, List<String>> families = {
    '5.5': ['5.5', '7.0', '9.0', '11.0', '14.3'],
    '6.30': ['6.30', '6.5', 'FM 8.0', 'CA50 8.0','FM 10.0', 'CA50 10.0', 'FM 12.5', 'CA50 12.5', 'FM 16.0', 'CA50 16.0'],
  };

  static const Map<String, String> bitolaDisplay = {
    '5.5': 'FM 5.5',
    '7.0': 'FM 7.0',
    '9.0': 'FM 9.0',
    '11.0': 'FM 11.0',
    '14.3': 'FM 14.3',
    '6.30': 'CA50 6.30',
    '6.5': 'FM 6.5',
    'FM 8.0': 'FM 8.0',
    'CA50 8.0': 'CA50 8.0',
    'FM 10.0': 'FM 10.0',
    'CA50 10.0': 'CA50 10.0',
    'FM 12.5': 'FM 12.5',
    'CA50 12.5': 'CA50 12.5',
    'FM 16.0': 'FM 16.0',
    'CA50 16.0': 'CA50 16.0',
    
  };

  static Map<String, List<Map<String, dynamic>>> valoresPadrao = {
      '5.5': [
    //desbartador
    {'luzPadrao': 15.0, 'profundidadeCanalPadrao': 47.5, 'alturaPadrao': 110.0, 'fatorDesgaste': 1.0, 'gaiola': '1V', 'forma': 'Retangular'},
    {'luzPadrao': 15.0, 'profundidadeCanalPadrao': 54.0, 'alturaPadrao': 123.0, 'fatorDesgaste': 1.0, 'gaiola': '2H', 'forma': 'Quadrada'},
    {'luzPadrao': 15.0, 'profundidadeCanalPadrao': 34.5, 'alturaPadrao': 84.0, 'fatorDesgaste': 1.0, 'gaiola': '3V', 'forma': 'Oval'},
    {'luzPadrao': 10.0, 'profundidadeCanalPadrao': 45.0, 'alturaPadrao': 100.0, 'fatorDesgaste': 1.0, 'gaiola': '4H', 'forma': 'Redondo'},
    {'luzPadrao': 10.0, 'profundidadeCanalPadrao': 23.0, 'alturaPadrao': 56.0, 'fatorDesgaste': 1.0, 'gaiola': '5V', 'forma': 'Oval'},
    {'luzPadrao': 6.0, 'profundidadeCanalPadrao': 33.0, 'alturaPadrao': 72.0, 'fatorDesgaste': 1.0, 'gaiola': '6H', 'forma': 'Redondo'},
    //intermediario
    {'luzPadrao': 13.0, 'profundidadeCanalPadrao': 15.0, 'alturaPadrao': 43.0, 'fatorDesgaste': 1.0, 'gaiola': '7H', 'forma': 'Oval'},
    {'luzPadrao': 15.0, 'profundidadeCanalPadrao': 20.0, 'alturaPadrao': 55.0, 'fatorDesgaste': 1.0, 'gaiola': '8V', 'forma': 'Redondo'},
    {'luzPadrao': 10.5, 'profundidadeCanalPadrao': 11.0, 'alturaPadrao': 32.5, 'fatorDesgaste': 1.0, 'gaiola': '9H', 'forma': 'Oval'},
    {'luzPadrao': 13.0, 'profundidadeCanalPadrao': 15.0, 'alturaPadrao': 43.0, 'fatorDesgaste': 1.0, 'gaiola': '10V', 'forma': 'Redondo'},
    {'luzPadrao': 12.0, 'profundidadeCanalPadrao': 6.5, 'alturaPadrao': 25.0, 'fatorDesgaste': 1.0, 'gaiola': '11H', 'forma': 'Oval'},
    {'luzPadrao': 9.0, 'profundidadeCanalPadrao': 12.5, 'alturaPadrao': 34.0, 'fatorDesgaste': 1.0, 'gaiola': '12V', 'forma': 'Redondo'},
    //pre-acabado
    {'luzPadrao': 4.20, 'profundidadeCanalPadrao': 7.0, 'alturaPadrao': 18.20, 'fatorDesgaste': 1.0, 'gaiola': '13H', 'forma': 'Oval'},
    {'luzPadrao': 4.20, 'profundidadeCanalPadrao': 10.50, 'alturaPadrao': 25.20, 'fatorDesgaste': 1.0, 'gaiola': '14V', 'forma': 'Redondo'},
    {'luzPadrao': 3.10, 'profundidadeCanalPadrao': 5.40, 'alturaPadrao': 13.90, 'fatorDesgaste': 1.0, 'gaiola': '15H', 'forma': 'Oval'},
    {'luzPadrao': 2.50, 'profundidadeCanalPadrao': 9.00, 'alturaPadrao': 20.50, 'fatorDesgaste': 1.0, 'gaiola': '16V', 'forma': 'Redondo'},
    {'luzPadrao': 2.80, 'profundidadeCanalPadrao': 4.50, 'alturaPadrao': 11.80, 'fatorDesgaste': 1.0, 'gaiola': '17H', 'forma': 'Oval'},
    {'luzPadrao': 2.80, 'profundidadeCanalPadrao': 7.00, 'alturaPadrao': 16.80, 'fatorDesgaste': 1.0, 'gaiola': '18V', 'forma': 'Redondo'},
    //bloco
    {'luzPadrao': 1.10, 'profundidadeCanalPadrao': 4.60, 'alturaPadrao': 10.30, 'fatorDesgaste': 1.0, 'gaiola': '19', 'forma': 'Oval'},
    {'luzPadrao': 0.90, 'profundidadeCanalPadrao': 6.25, 'alturaPadrao': 13.40, 'fatorDesgaste': 1.0, 'gaiola': '20', 'forma': 'Redondo'},
    {'luzPadrao': 0.90, 'profundidadeCanalPadrao': 3.60, 'alturaPadrao': 8.10, 'fatorDesgaste': 1.0, 'gaiola': '21', 'forma': 'Oval'},
    {'luzPadrao': 1.10, 'profundidadeCanalPadrao': 4.85, 'alturaPadrao': 10.80, 'fatorDesgaste': 1.0, 'gaiola': '22', 'forma': 'Redondo'},
    {'luzPadrao': 1.30, 'profundidadeCanalPadrao': 2.60, 'alturaPadrao': 6.50, 'fatorDesgaste': 1.0, 'gaiola': '23', 'forma': 'Oval'},
    {'luzPadrao': 1.10, 'profundidadeCanalPadrao': 3.80, 'alturaPadrao': 8.70, 'fatorDesgaste': 1.0, 'gaiola': '24', 'forma': 'Redondo'},
    {'luzPadrao': 1.10, 'profundidadeCanalPadrao': 1.90, 'alturaPadrao': 4.90, 'fatorDesgaste': 1.0, 'gaiola': '25', 'forma': 'Oval'},
    {'luzPadrao': 0.80, 'profundidadeCanalPadrao': 3.04, 'alturaPadrao': 6.88, 'fatorDesgaste': 1.0, 'gaiola': '26', 'forma': 'Oval'},
    {'luzPadrao': 0.90, 'profundidadeCanalPadrao': 1.55, 'alturaPadrao': 4.00, 'fatorDesgaste': 1.0, 'gaiola': '27', 'forma': 'Oval'},
    {'luzPadrao': 1.15, 'profundidadeCanalPadrao': 2.28, 'alturaPadrao': 5.71, 'fatorDesgaste': 1.0, 'gaiola': '28', 'forma': 'Oval'},
    ],
    //outra bitola
    '7.0': [
    //desbartador
    {'luzPadrao': 15.0, 'profundidadeCanalPadrao': 47.5, 'alturaPadrao': 110.0, 'fatorDesgaste': 1.0, 'gaiola': '1V', 'forma': 'Retangular'},
    {'luzPadrao': 15.0, 'profundidadeCanalPadrao': 54.0, 'alturaPadrao': 123.0, 'fatorDesgaste': 1.0, 'gaiola': '2H', 'forma': 'Quadrada'},
    {'luzPadrao': 15.0, 'profundidadeCanalPadrao': 34.5, 'alturaPadrao': 84.0, 'fatorDesgaste': 1.0, 'gaiola': '3V', 'forma': 'Oval'},
    {'luzPadrao': 10.0, 'profundidadeCanalPadrao': 45.0, 'alturaPadrao': 100.0, 'fatorDesgaste': 1.0, 'gaiola': '4H', 'forma': 'Redondo'},
    {'luzPadrao': 10.0, 'profundidadeCanalPadrao': 23.0, 'alturaPadrao': 56.0, 'fatorDesgaste': 1.0, 'gaiola': '5V', 'forma': 'Oval'},
    {'luzPadrao': 6.0, 'profundidadeCanalPadrao': 33.0, 'alturaPadrao': 72.0, 'fatorDesgaste': 1.0, 'gaiola': '6H', 'forma': 'Redondo'},
    //intermediario
    {'luzPadrao': 13.0, 'profundidadeCanalPadrao': 15.0, 'alturaPadrao': 43.0, 'fatorDesgaste': 1.0, 'gaiola': '7H', 'forma': 'Oval'},
    {'luzPadrao': 15.0, 'profundidadeCanalPadrao': 20.0, 'alturaPadrao': 55.0, 'fatorDesgaste': 1.0, 'gaiola': '8V', 'forma': 'Redondo'},
    {'luzPadrao': 10.5, 'profundidadeCanalPadrao': 11.0, 'alturaPadrao': 32.5, 'fatorDesgaste': 1.0, 'gaiola': '9H', 'forma': 'Oval'},
    {'luzPadrao': 13.0, 'profundidadeCanalPadrao': 15.0, 'alturaPadrao': 43.0, 'fatorDesgaste': 1.0, 'gaiola': '10V', 'forma': 'Redondo'},
    {'luzPadrao': 12.0, 'profundidadeCanalPadrao': 6.5, 'alturaPadrao': 25.0, 'fatorDesgaste': 1.0, 'gaiola': '11H', 'forma': 'Oval'},
    {'luzPadrao': 9.0, 'profundidadeCanalPadrao': 12.5, 'alturaPadrao': 34.0, 'fatorDesgaste': 1.0, 'gaiola': '12V', 'forma': 'Redondo'},
    //pre-acabado
    {'luzPadrao': 5.90, 'profundidadeCanalPadrao': 7.0, 'alturaPadrao': 19.90, 'fatorDesgaste': 1.0, 'gaiola': '13H', 'forma': 'Oval'},
    {'luzPadrao': 5.20, 'profundidadeCanalPadrao': 10.50, 'alturaPadrao': 26.20, 'fatorDesgaste': 1.0, 'gaiola': '14V', 'forma': 'Redondo'},
    {'luzPadrao': 0.00, 'profundidadeCanalPadrao': 0.00, 'alturaPadrao': 0.00, 'fatorDesgaste': 0.00, 'gaiola': 'DUMMY', 'forma': 'DUMMY'},
    {'luzPadrao': 4.50, 'profundidadeCanalPadrao': 5.40, 'alturaPadrao': 15.30, 'fatorDesgaste': 1.0, 'gaiola': '15H', 'forma': 'Redondo'},
    {'luzPadrao': 0.00, 'profundidadeCanalPadrao': 0.00, 'alturaPadrao': 0.00, 'fatorDesgaste': 1.0, 'gaiola': 'DUMMY', 'forma': 'DUMMY'},
    {'luzPadrao': 3.50, 'profundidadeCanalPadrao': 9.00, 'alturaPadrao': 21.50, 'fatorDesgaste': 1.0, 'gaiola': '16V', 'forma': 'Redondo'},
     //bloco
    {'luzPadrao': 4.90, 'profundidadeCanalPadrao': 3.95, 'alturaPadrao': 12.80, 'fatorDesgaste': 1.0, 'gaiola': '17', 'forma': 'Oval'},
    {'luzPadrao': 3.20, 'profundidadeCanalPadrao': 7.00, 'alturaPadrao': 17.20, 'fatorDesgaste': 1.0, 'gaiola': '18', 'forma': 'Redondo'},
    {'luzPadrao': 1.81, 'profundidadeCanalPadrao': 4.60, 'alturaPadrao': 11.01, 'fatorDesgaste': 1.0, 'gaiola': '21', 'forma': 'Oval'},
    {'luzPadrao': 1.30, 'profundidadeCanalPadrao': 6.25, 'alturaPadrao': 13.80, 'fatorDesgaste': 1.0, 'gaiola': '22', 'forma': 'Redondo'},
    {'luzPadrao': 1.30, 'profundidadeCanalPadrao': 3.60, 'alturaPadrao': 8.50, 'fatorDesgaste': 1.0, 'gaiola': '23', 'forma': 'Oval'},
    {'luzPadrao': 1.40, 'profundidadeCanalPadrao': 4.85, 'alturaPadrao': 11.10, 'fatorDesgaste': 1.0, 'gaiola': '24', 'forma': 'Redondo'},
    {'luzPadrao': 1.40, 'profundidadeCanalPadrao': 2.60, 'alturaPadrao': 6.60, 'fatorDesgaste': 1.0, 'gaiola': '25', 'forma': 'Oval'},
    {'luzPadrao': 1.30, 'profundidadeCanalPadrao': 3.80, 'alturaPadrao': 8.90, 'fatorDesgaste': 1.0, 'gaiola': '26', 'forma': 'Redondo'},
    {'luzPadrao': 1.40, 'profundidadeCanalPadrao': 1.90, 'alturaPadrao': 5.20, 'fatorDesgaste': 1.0, 'gaiola': '27', 'forma': 'Oval'},
    {'luzPadrao': 1.13, 'profundidadeCanalPadrao': 3.04, 'alturaPadrao': 7.21, 'fatorDesgaste': 1.0, 'gaiola': '28', 'forma': 'Redondo'},
    ],
    '9.0':  [
    //desbartador
    {'luzPadrao': 15.0, 'profundidadeCanalPadrao': 47.5, 'alturaPadrao': 110.0, 'fatorDesgaste': 1.0, 'gaiola': '1V', 'forma': 'Retangular'},
    {'luzPadrao': 15.0, 'profundidadeCanalPadrao': 54.0, 'alturaPadrao': 123.0, 'fatorDesgaste': 1.0, 'gaiola': '2H', 'forma': 'Quadrada'},
    {'luzPadrao': 15.0, 'profundidadeCanalPadrao': 34.5, 'alturaPadrao': 84.0, 'fatorDesgaste': 1.0, 'gaiola': '3V', 'forma': 'Oval'},
    {'luzPadrao': 10.0, 'profundidadeCanalPadrao': 45.0, 'alturaPadrao': 100.0, 'fatorDesgaste': 1.0, 'gaiola': '4H', 'forma': 'Redondo'},
    {'luzPadrao': 10.0, 'profundidadeCanalPadrao': 23.0, 'alturaPadrao': 56.0, 'fatorDesgaste': 1.0, 'gaiola': '5V', 'forma': 'Oval'},
    {'luzPadrao': 6.0, 'profundidadeCanalPadrao': 33.0, 'alturaPadrao': 72.0, 'fatorDesgaste': 1.0, 'gaiola': '6H', 'forma': 'Redondo'},
    //intermediario
    {'luzPadrao': 13.0, 'profundidadeCanalPadrao': 15.0, 'alturaPadrao': 43.0, 'fatorDesgaste': 1.0, 'gaiola': '7H', 'forma': 'Oval'},
    {'luzPadrao': 15.0, 'profundidadeCanalPadrao': 20.0, 'alturaPadrao': 55.0, 'fatorDesgaste': 1.0, 'gaiola': '8V', 'forma': 'Redondo'},
    {'luzPadrao': 10.5, 'profundidadeCanalPadrao': 11.0, 'alturaPadrao': 32.5, 'fatorDesgaste': 1.0, 'gaiola': '9H', 'forma': 'Oval'},
    {'luzPadrao': 13.0, 'profundidadeCanalPadrao': 15.0, 'alturaPadrao': 43.0, 'fatorDesgaste': 1.0, 'gaiola': '10V', 'forma': 'Redondo'},
    {'luzPadrao': 12.0, 'profundidadeCanalPadrao': 6.5, 'alturaPadrao': 25.0, 'fatorDesgaste': 1.0, 'gaiola': '11H', 'forma': 'Oval'},
    {'luzPadrao': 9.0, 'profundidadeCanalPadrao': 12.5, 'alturaPadrao': 34.0, 'fatorDesgaste': 1.0, 'gaiola': '12V', 'forma': 'Redondo'},
    //pre-acabado
    {'luzPadrao': 7.00, 'profundidadeCanalPadrao': 7.0, 'alturaPadrao': 21.00, 'fatorDesgaste': 1.0, 'gaiola': '13H', 'forma': 'Oval'},
    {'luzPadrao': 6.00, 'profundidadeCanalPadrao': 10.50, 'alturaPadrao': 27.00, 'fatorDesgaste': 1.0, 'gaiola': '14V', 'forma': 'Redondo'},
    {'luzPadrao': 0.00, 'profundidadeCanalPadrao': 0.00, 'alturaPadrao': 0.00, 'fatorDesgaste': 0.00, 'gaiola': 'DUMMY', 'forma': 'DUMMY'},
    {'luzPadrao': 5.50, 'profundidadeCanalPadrao': 5.40, 'alturaPadrao': 16.30, 'fatorDesgaste': 1.0, 'gaiola': '15H', 'forma': 'Redondo'},
    {'luzPadrao': 0.00, 'profundidadeCanalPadrao': 0.00, 'alturaPadrao': 0.00, 'fatorDesgaste': 1.0, 'gaiola': 'DUMMY', 'forma': 'DUMMY'},
    {'luzPadrao': 4.50, 'profundidadeCanalPadrao': 9.00, 'alturaPadrao': 22.50, 'fatorDesgaste': 1.0, 'gaiola': '16V', 'forma': 'Redondo'},
     //bloco
    {'luzPadrao': 4.90, 'profundidadeCanalPadrao': 3.95, 'alturaPadrao': 12.80, 'fatorDesgaste': 1.0, 'gaiola': '17', 'forma': 'Oval'},
    {'luzPadrao': 3.25, 'profundidadeCanalPadrao': 7.00, 'alturaPadrao': 17.80, 'fatorDesgaste': 1.0, 'gaiola': '18', 'forma': 'Redondo'},
    {'luzPadrao': 2.10, 'profundidadeCanalPadrao': 4.60, 'alturaPadrao': 11.30, 'fatorDesgaste': 1.0, 'gaiola': '21', 'forma': 'Oval'},
    {'luzPadrao': 1.80, 'profundidadeCanalPadrao': 6.25, 'alturaPadrao': 14.30, 'fatorDesgaste': 1.0, 'gaiola': '22', 'forma': 'Redondo'},
    {'luzPadrao': 2.00, 'profundidadeCanalPadrao': 3.60, 'alturaPadrao': 9.20, 'fatorDesgaste': 1.0, 'gaiola': '23', 'forma': 'Oval'},
    {'luzPadrao': 1.90, 'profundidadeCanalPadrao': 4.85, 'alturaPadrao': 11.60, 'fatorDesgaste': 1.0, 'gaiola': '24', 'forma': 'Redondo'},
    {'luzPadrao': 1.80, 'profundidadeCanalPadrao': 2.60, 'alturaPadrao': 7.00, 'fatorDesgaste': 1.0, 'gaiola': '25', 'forma': 'Oval'},
    {'luzPadrao': 1.50, 'profundidadeCanalPadrao': 3.80, 'alturaPadrao': 9.10, 'fatorDesgaste': 1.0, 'gaiola': '26', 'forma': 'Redondo'},
    {'luzPadrao': 0.00, 'profundidadeCanalPadrao': 0.00, 'alturaPadrao': 0.00, 'fatorDesgaste': 0.00, 'gaiola': 'DUMMY', 'forma': 'Oval'},
    {'luzPadrao': 0.00, 'profundidadeCanalPadrao': 0.00, 'alturaPadrao': 0.00, 'fatorDesgaste': 0.00, 'gaiola': 'DUMMY', 'forma': 'Redondo'},
    ],
    '14.3':[ 
      //desbartador
    {'luzPadrao': 15.0, 'profundidadeCanalPadrao': 47.5, 'alturaPadrao': 110.0, 'fatorDesgaste': 1.0, 'gaiola': '1V', 'forma': 'Retangular'},
    {'luzPadrao': 15.0, 'profundidadeCanalPadrao': 54.0, 'alturaPadrao': 123.0, 'fatorDesgaste': 1.0, 'gaiola': '2H', 'forma': 'Quadrada'},
    {'luzPadrao': 15.0, 'profundidadeCanalPadrao': 34.5, 'alturaPadrao': 84.0, 'fatorDesgaste': 1.0, 'gaiola': '3V', 'forma': 'Oval'},
    {'luzPadrao': 10.0, 'profundidadeCanalPadrao': 45.0, 'alturaPadrao': 100.0, 'fatorDesgaste': 1.0, 'gaiola': '4H', 'forma': 'Redondo'},
    {'luzPadrao': 10.0, 'profundidadeCanalPadrao': 23.0, 'alturaPadrao': 56.0, 'fatorDesgaste': 1.0, 'gaiola': '5V', 'forma': 'Oval'},
    {'luzPadrao': 6.0, 'profundidadeCanalPadrao': 33.0, 'alturaPadrao': 72.0, 'fatorDesgaste': 1.0, 'gaiola': '6H', 'forma': 'Redondo'},
    //intermediario
    {'luzPadrao': 13.0, 'profundidadeCanalPadrao': 15.0, 'alturaPadrao': 43.0, 'fatorDesgaste': 1.0, 'gaiola': '7H', 'forma': 'Oval'},
    {'luzPadrao': 15.0, 'profundidadeCanalPadrao': 20.0, 'alturaPadrao': 55.0, 'fatorDesgaste': 1.0, 'gaiola': '8V', 'forma': 'Redondo'},
    {'luzPadrao': 10.5, 'profundidadeCanalPadrao': 11.0, 'alturaPadrao': 32.5, 'fatorDesgaste': 1.0, 'gaiola': '9H', 'forma': 'Oval'},
    {'luzPadrao': 13.0, 'profundidadeCanalPadrao': 15.0, 'alturaPadrao': 43.0, 'fatorDesgaste': 1.0, 'gaiola': '10V', 'forma': 'Redondo'},
    {'luzPadrao': 12.0, 'profundidadeCanalPadrao': 6.5, 'alturaPadrao': 25.0, 'fatorDesgaste': 1.0, 'gaiola': '11H', 'forma': 'Oval'},
    {'luzPadrao': 9.0, 'profundidadeCanalPadrao': 12.5, 'alturaPadrao': 34.0, 'fatorDesgaste': 1.0, 'gaiola': '12V', 'forma': 'Redondo'},
    //pre-acabado
    {'luzPadrao': 7.00, 'profundidadeCanalPadrao': 7.0, 'alturaPadrao': 21.00, 'fatorDesgaste': 1.0, 'gaiola': '13H', 'forma': 'Oval'},
    {'luzPadrao': 6.00, 'profundidadeCanalPadrao': 10.50, 'alturaPadrao': 27.00, 'fatorDesgaste': 1.0, 'gaiola': '14V', 'forma': 'Redondo'},
    {'luzPadrao': 0.00, 'profundidadeCanalPadrao': 0.00, 'alturaPadrao': 0.00, 'fatorDesgaste': 0.00, 'gaiola': 'DUMMY', 'forma': 'DUMMY'},
    {'luzPadrao': 5.50, 'profundidadeCanalPadrao': 5.40, 'alturaPadrao': 16.30, 'fatorDesgaste': 1.0, 'gaiola': '15H', 'forma': 'Redondo'},
    {'luzPadrao': 0.00, 'profundidadeCanalPadrao': 0.00, 'alturaPadrao': 0.00, 'fatorDesgaste': 1.0, 'gaiola': 'DUMMY', 'forma': 'DUMMY'},
    {'luzPadrao': 4.50, 'profundidadeCanalPadrao': 9.00, 'alturaPadrao': 22.50, 'fatorDesgaste': 1.0, 'gaiola': '16V', 'forma': 'Redondo'},
     //bloco
    {'luzPadrao': 5.0, 'profundidadeCanalPadrao': 3.95, 'alturaPadrao': 12.90, 'fatorDesgaste': 1.0, 'gaiola': '17', 'forma': 'Oval'},
    {'luzPadrao': 3.40, 'profundidadeCanalPadrao': 7.00, 'alturaPadrao': 17.40, 'fatorDesgaste': 1.0, 'gaiola': '18', 'forma': 'Redondo'},
    {'luzPadrao': 2.20, 'profundidadeCanalPadrao': 4.60, 'alturaPadrao': 11.40, 'fatorDesgaste': 1.0, 'gaiola': '21', 'forma': 'Oval'},
    {'luzPadrao': 1.00, 'profundidadeCanalPadrao': 6.71, 'alturaPadrao': 14.42, 'fatorDesgaste': 1.0, 'gaiola': '22', 'forma': 'Redondo'},
    {'luzPadrao': 0.00, 'profundidadeCanalPadrao': 0.00, 'alturaPadrao': 0.00, 'fatorDesgaste': 1.0, 'gaiola': 'DUMMY', 'DUMMY': 'DUMMY'},
    {'luzPadrao': 0.00, 'profundidadeCanalPadrao': 0.00, 'alturaPadrao': 0.00, 'fatorDesgaste': 1.0, 'gaiola': 'DUMMY', 'DUMMY': 'DUMMY'},
    {'luzPadrao': 0.00, 'profundidadeCanalPadrao': 0.00, 'alturaPadrao': 0.00, 'fatorDesgaste': 1.0, 'gaiola': 'DUMMY', 'DUMMY': 'DUMMY'},
    {'luzPadrao': 0.00, 'profundidadeCanalPadrao': 0.00, 'alturaPadrao': 0.00, 'fatorDesgaste': 1.0, 'gaiola': 'DUMMY', 'DUMMY': 'DUMMY'},
    {'luzPadrao': 0.00, 'profundidadeCanalPadrao': 0.00, 'alturaPadrao': 0.00, 'fatorDesgaste': 0.00, 'gaiola': 'DUMMY', 'DUMMY': 'DUMMY'},
    {'luzPadrao': 0.00, 'profundidadeCanalPadrao': 0.00, 'alturaPadrao': 0.00, 'fatorDesgaste': 0.00, 'gaiola': 'DUMMY', 'DUMMY': 'DUMMY'},
    ],
    '6.30': [
       //desbartador
    {'luzPadrao': 15.0, 'profundidadeCanalPadrao': 47.5, 'alturaPadrao': 110.0, 'fatorDesgaste': 1.0, 'gaiola': '1V', 'forma': 'Retangular'},
    {'luzPadrao': 15.0, 'profundidadeCanalPadrao': 54.0, 'alturaPadrao': 123.0, 'fatorDesgaste': 1.0, 'gaiola': '2H', 'forma': 'Quadrada'},
    {'luzPadrao': 15.0, 'profundidadeCanalPadrao': 34.5, 'alturaPadrao': 84.0, 'fatorDesgaste': 1.0, 'gaiola': '3V', 'forma': 'Oval'},
    {'luzPadrao': 10.0, 'profundidadeCanalPadrao': 45.0, 'alturaPadrao': 100.0, 'fatorDesgaste': 1.0, 'gaiola': '4H', 'forma': 'Redondo'},
    {'luzPadrao': 10.0, 'profundidadeCanalPadrao': 23.0, 'alturaPadrao': 56.0, 'fatorDesgaste': 1.0, 'gaiola': '5V', 'forma': 'Oval'},
    {'luzPadrao': 6.0, 'profundidadeCanalPadrao': 33.0, 'alturaPadrao': 72.0, 'fatorDesgaste': 1.0, 'gaiola': '6H', 'forma': 'Redondo'},
    //intermediario
    {'luzPadrao': 13.0, 'profundidadeCanalPadrao': 15.0, 'alturaPadrao': 43.0, 'fatorDesgaste': 1.0, 'gaiola': '7H', 'forma': 'Oval'},
    {'luzPadrao': 15.0, 'profundidadeCanalPadrao': 20.0, 'alturaPadrao': 55.0, 'fatorDesgaste': 1.0, 'gaiola': '8V', 'forma': 'Redondo'},
    {'luzPadrao': 10.5, 'profundidadeCanalPadrao': 11.0, 'alturaPadrao': 32.5, 'fatorDesgaste': 1.0, 'gaiola': '9H', 'forma': 'Oval'},
    {'luzPadrao': 13.0, 'profundidadeCanalPadrao': 15.0, 'alturaPadrao': 43.0, 'fatorDesgaste': 1.0, 'gaiola': '10V', 'forma': 'Redondo'},
    {'luzPadrao': 12.0, 'profundidadeCanalPadrao': 6.5, 'alturaPadrao': 25.0, 'fatorDesgaste': 1.0, 'gaiola': '11H', 'forma': 'Oval'},
    {'luzPadrao': 9.0, 'profundidadeCanalPadrao': 12.5, 'alturaPadrao': 34.0, 'fatorDesgaste': 1.0, 'gaiola': '12V', 'forma': 'Redondo'},
    //pre-acabado
    {'luzPadrao': 7.90, 'profundidadeCanalPadrao': 7.0, 'alturaPadrao': 21.90, 'fatorDesgaste': 1.0, 'gaiola': '13H', 'forma': 'Oval'},
    {'luzPadrao': 4.50, 'profundidadeCanalPadrao': 11.50, 'alturaPadrao': 27.50, 'fatorDesgaste': 1.0, 'gaiola': '14V', 'forma': 'Redondo'},
    {'luzPadrao': 7.10, 'profundidadeCanalPadrao': 5.40, 'alturaPadrao': 38.30, 'fatorDesgaste': 0.00, 'gaiola': '15H', 'forma': 'Oval'},
    {'luzPadrao': 3.40, 'profundidadeCanalPadrao': 9.75, 'alturaPadrao': 22.90, 'fatorDesgaste': 1.0, 'gaiola': '16V', 'forma': 'Redondo'},
    {'luzPadrao': 4.60, 'profundidadeCanalPadrao': 4.55, 'alturaPadrao': 29.20, 'fatorDesgaste': 1.0, 'gaiola': '17H', 'forma': 'Oval'},
    {'luzPadrao': 3.30, 'profundidadeCanalPadrao': 7.90, 'alturaPadrao': 19.10, 'fatorDesgaste': 1.0, 'gaiola': '18V', 'forma': 'Redondo'},
     //bloco
    {'luzPadrao': 0.90, 'profundidadeCanalPadrao': 5.60, 'alturaPadrao': 12.10, 'fatorDesgaste': 1.0, 'gaiola': '17', 'forma': 'Oval'},
    {'luzPadrao': 1.10, 'profundidadeCanalPadrao': 7.00, 'alturaPadrao': 15.10, 'fatorDesgaste': 1.0, 'gaiola': '18', 'forma': 'Redondo'},
    {'luzPadrao': 0.90, 'profundidadeCanalPadrao': 4.60, 'alturaPadrao': 10.10, 'fatorDesgaste': 1.0, 'gaiola': '21', 'forma': 'Oval'},
    {'luzPadrao': 1.60, 'profundidadeCanalPadrao': 5.20, 'alturaPadrao': 12.00, 'fatorDesgaste': 1.0, 'gaiola': '22', 'forma': 'Redondo'},
    {'luzPadrao': 1.00, 'profundidadeCanalPadrao': 3.40, 'alturaPadrao': 7.80, 'fatorDesgaste': 1.0, 'gaiola': '23', 'forma': 'Oval'},
    {'luzPadrao': 1.30, 'profundidadeCanalPadrao': 4.20, 'alturaPadrao': 9.70, 'fatorDesgaste': 1.0, 'gaiola': '24', 'forma': 'Redondo'},
    {'luzPadrao': 1.15, 'profundidadeCanalPadrao':2.30, 'alturaPadrao': 5.75, 'fatorDesgaste': 1.0, 'gaiola': '25', 'forma': 'Oval'},
    {'luzPadrao': 0.80, 'profundidadeCanalPadrao': 3.65, 'alturaPadrao': 8.10, 'fatorDesgaste': 1.0, 'gaiola': '26', 'forma': 'Redondo'},
    {'luzPadrao': 0.80, 'profundidadeCanalPadrao': 1.90, 'alturaPadrao': 4.60, 'fatorDesgaste': 0.00, 'gaiola': '27', 'forma': 'Oval'},
    {'luzPadrao': 0.95, 'profundidadeCanalPadrao': 2.58, 'alturaPadrao': 4.75, 'fatorDesgaste': 0.00, 'gaiola': '28', 'forma': 'Redondo'},
    ],
    '6.5': [
       //desbartador
    {'luzPadrao': 15.0, 'profundidadeCanalPadrao': 47.5, 'alturaPadrao': 110.0, 'fatorDesgaste': 1.0, 'gaiola': '1V', 'forma': 'Retangular'},
    {'luzPadrao': 15.0, 'profundidadeCanalPadrao': 54.0, 'alturaPadrao': 123.0, 'fatorDesgaste': 1.0, 'gaiola': '2H', 'forma': 'Quadrada'},
    {'luzPadrao': 15.0, 'profundidadeCanalPadrao': 34.5, 'alturaPadrao': 84.0, 'fatorDesgaste': 1.0, 'gaiola': '3V', 'forma': 'Oval'},
    {'luzPadrao': 10.0, 'profundidadeCanalPadrao': 45.0, 'alturaPadrao': 100.0, 'fatorDesgaste': 1.0, 'gaiola': '4H', 'forma': 'Redondo'},
    {'luzPadrao': 10.0, 'profundidadeCanalPadrao': 23.0, 'alturaPadrao': 56.0, 'fatorDesgaste': 1.0, 'gaiola': '5V', 'forma': 'Oval'},
    {'luzPadrao': 6.0, 'profundidadeCanalPadrao': 33.0, 'alturaPadrao': 72.0, 'fatorDesgaste': 1.0, 'gaiola': '6H', 'forma': 'Redondo'},
    //intermediario
    {'luzPadrao': 13.0, 'profundidadeCanalPadrao': 15.0, 'alturaPadrao': 43.0, 'fatorDesgaste': 1.0, 'gaiola': '7H', 'forma': 'Oval'},
    {'luzPadrao': 15.0, 'profundidadeCanalPadrao': 20.0, 'alturaPadrao': 55.0, 'fatorDesgaste': 1.0, 'gaiola': '8V', 'forma': 'Redondo'},
    {'luzPadrao': 10.5, 'profundidadeCanalPadrao': 11.0, 'alturaPadrao': 32.5, 'fatorDesgaste': 1.0, 'gaiola': '9H', 'forma': 'Oval'},
    {'luzPadrao': 13.0, 'profundidadeCanalPadrao': 15.0, 'alturaPadrao': 43.0, 'fatorDesgaste': 1.0, 'gaiola': '10V', 'forma': 'Redondo'},
    {'luzPadrao': 12.0, 'profundidadeCanalPadrao': 6.5, 'alturaPadrao': 25.0, 'fatorDesgaste': 1.0, 'gaiola': '11H', 'forma': 'Oval'},
    {'luzPadrao': 9.0, 'profundidadeCanalPadrao': 12.5, 'alturaPadrao': 34.0, 'fatorDesgaste': 1.0, 'gaiola': '12V', 'forma': 'Redondo'},
    //pre-acabado
    {'luzPadrao': 4.20, 'profundidadeCanalPadrao': 7.0, 'alturaPadrao': 18.20, 'fatorDesgaste': 1.0, 'gaiola': '13H', 'forma': 'Oval'},
    {'luzPadrao': 4.20, 'profundidadeCanalPadrao': 10.50, 'alturaPadrao': 25.20, 'fatorDesgaste': 1.0, 'gaiola': '14V', 'forma': 'Redondo'},
    {'luzPadrao': 0.00, 'profundidadeCanalPadrao': 0.00, 'alturaPadrao': 0.00, 'fatorDesgaste': 0.00, 'gaiola': 'DUMMY', 'forma': 'DUMMY'},
    {'luzPadrao': 5.20, 'profundidadeCanalPadrao': 4.55, 'alturaPadrao': 14.30, 'fatorDesgaste': 1.0, 'gaiola': '17H', 'forma': 'Oval'},
    {'luzPadrao': 0.00, 'profundidadeCanalPadrao': 0.00, 'alturaPadrao': 0.00, 'fatorDesgaste': 0.0, 'gaiola': 'DUMMY', 'forma': 'DUMMY'},
    {'luzPadrao': 4.50, 'profundidadeCanalPadrao': 7.90, 'alturaPadrao': 20.30, 'fatorDesgaste': 1.0, 'gaiola': '18V', 'forma': 'Redondo'},
     //bloco
    {'luzPadrao': 1.80, 'profundidadeCanalPadrao': 5.60, 'alturaPadrao': 13.00, 'fatorDesgaste': 1.0, 'gaiola': '17', 'forma': 'Oval'},
    {'luzPadrao': 2.00, 'profundidadeCanalPadrao': 7.00, 'alturaPadrao': 16.00, 'fatorDesgaste': 1.0, 'gaiola': '18', 'forma': 'Redondo'},
    {'luzPadrao': 1.30, 'profundidadeCanalPadrao': 4.60, 'alturaPadrao': 10.50, 'fatorDesgaste': 1.0, 'gaiola': '21', 'forma': 'Oval'},
    {'luzPadrao': 2.35, 'profundidadeCanalPadrao': 5.20, 'alturaPadrao': 12.75, 'fatorDesgaste': 1.0, 'gaiola': '22', 'forma': 'Redondo'},
    {'luzPadrao': 1.50, 'profundidadeCanalPadrao': 3.40, 'alturaPadrao': 8.30, 'fatorDesgaste': 1.0, 'gaiola': '23', 'forma': 'Oval'},
    {'luzPadrao': 1.80, 'profundidadeCanalPadrao': 4.20, 'alturaPadrao': 10.20, 'fatorDesgaste': 1.0, 'gaiola': '24', 'forma': 'Redondo'},
    {'luzPadrao': 1.65, 'profundidadeCanalPadrao':2.30, 'alturaPadrao': 6.25, 'fatorDesgaste': 1.0, 'gaiola': '25', 'forma': 'Oval'},
    {'luzPadrao': 1.10, 'profundidadeCanalPadrao': 3.65, 'alturaPadrao': 8.40, 'fatorDesgaste': 1.0, 'gaiola': '26', 'forma': 'Redondo'},
    {'luzPadrao': 1.20, 'profundidadeCanalPadrao': 1.90, 'alturaPadrao': 5.00, 'fatorDesgaste': 1.00, 'gaiola': '27', 'forma': 'Oval'},
    {'luzPadrao': 1.30, 'profundidadeCanalPadrao': 2.71, 'alturaPadrao': 6.72, 'fatorDesgaste': 1.00, 'gaiola': '28', 'forma': 'Redondo'},
    ],
    'FM 8.0': [
       //desbartador
    {'luzPadrao': 15.0, 'profundidadeCanalPadrao': 47.5, 'alturaPadrao': 110.0, 'fatorDesgaste': 1.0, 'gaiola': '1V', 'forma': 'Retangular'},
    {'luzPadrao': 15.0, 'profundidadeCanalPadrao': 54.0, 'alturaPadrao': 123.0, 'fatorDesgaste': 1.0, 'gaiola': '2H', 'forma': 'Quadrada'},
    {'luzPadrao': 15.0, 'profundidadeCanalPadrao': 34.5, 'alturaPadrao': 84.0, 'fatorDesgaste': 1.0, 'gaiola': '3V', 'forma': 'Oval'},
    {'luzPadrao': 10.0, 'profundidadeCanalPadrao': 45.0, 'alturaPadrao': 100.0, 'fatorDesgaste': 1.0, 'gaiola': '4H', 'forma': 'Redondo'},
    {'luzPadrao': 10.0, 'profundidadeCanalPadrao': 23.0, 'alturaPadrao': 56.0, 'fatorDesgaste': 1.0, 'gaiola': '5V', 'forma': 'Oval'},
    {'luzPadrao': 6.0, 'profundidadeCanalPadrao': 33.0, 'alturaPadrao': 72.0, 'fatorDesgaste': 1.0, 'gaiola': '6H', 'forma': 'Redondo'},
    //intermediario
    {'luzPadrao': 13.0, 'profundidadeCanalPadrao': 15.0, 'alturaPadrao': 43.0, 'fatorDesgaste': 1.0, 'gaiola': '7H', 'forma': 'Oval'},
    {'luzPadrao': 15.0, 'profundidadeCanalPadrao': 20.0, 'alturaPadrao': 55.0, 'fatorDesgaste': 1.0, 'gaiola': '8V', 'forma': 'Redondo'},
    {'luzPadrao': 10.5, 'profundidadeCanalPadrao': 11.0, 'alturaPadrao': 32.5, 'fatorDesgaste': 1.0, 'gaiola': '9H', 'forma': 'Oval'},
    {'luzPadrao': 13.0, 'profundidadeCanalPadrao': 15.0, 'alturaPadrao': 43.0, 'fatorDesgaste': 1.0, 'gaiola': '10V', 'forma': 'Redondo'},
    {'luzPadrao': 12.0, 'profundidadeCanalPadrao': 6.5, 'alturaPadrao': 25.0, 'fatorDesgaste': 1.0, 'gaiola': '11H', 'forma': 'Oval'},
    {'luzPadrao': 9.0, 'profundidadeCanalPadrao': 12.5, 'alturaPadrao': 34.0, 'fatorDesgaste': 1.0, 'gaiola': '12V', 'forma': 'Redondo'},
    //pre-acabado
    {'luzPadrao': 9.60, 'profundidadeCanalPadrao': 7.0, 'alturaPadrao': 23.60, 'fatorDesgaste': 1.0, 'gaiola': '13H', 'forma': 'Oval'},
    {'luzPadrao': 5.70, 'profundidadeCanalPadrao': 11.50, 'alturaPadrao': 28.70, 'fatorDesgaste': 1.0, 'gaiola': '14V', 'forma': 'Redondo'},
    {'luzPadrao': 0.00, 'profundidadeCanalPadrao': 0.00, 'alturaPadrao': 0.00, 'fatorDesgaste': 0.00, 'gaiola': 'DUMMY', 'forma': 'DUMMY'},
    {'luzPadrao': 8.00, 'profundidadeCanalPadrao': 5.40, 'alturaPadrao': 18.80, 'fatorDesgaste': 1.0, 'gaiola': '17H', 'forma': 'Oval'},
    {'luzPadrao': 0.00, 'profundidadeCanalPadrao': 0.00, 'alturaPadrao': 0.00, 'fatorDesgaste': 0.0, 'gaiola': 'DUMMY', 'forma': 'DUMMY'},
    {'luzPadrao': 4.50, 'profundidadeCanalPadrao': 9.75, 'alturaPadrao': 24.00, 'fatorDesgaste': 1.0, 'gaiola': '18V', 'forma': 'Redondo'},
     //bloco
    {'luzPadrao': 5.70, 'profundidadeCanalPadrao': 4.55, 'alturaPadrao': 14.80, 'fatorDesgaste': 1.0, 'gaiola': '17', 'forma': 'Oval'},
    {'luzPadrao': 3.65, 'profundidadeCanalPadrao': 7.90, 'alturaPadrao': 19.45, 'fatorDesgaste': 1.0, 'gaiola': '18', 'forma': 'Redondo'},
    {'luzPadrao': 1.90, 'profundidadeCanalPadrao': 5.60, 'alturaPadrao': 13.10, 'fatorDesgaste': 1.0, 'gaiola': '21', 'forma': 'Oval'},
    {'luzPadrao': 1.90, 'profundidadeCanalPadrao': 7.00, 'alturaPadrao': 15.90, 'fatorDesgaste': 1.0, 'gaiola': '22', 'forma': 'Redondo'},
    {'luzPadrao': 1.30, 'profundidadeCanalPadrao': 4.60, 'alturaPadrao': 10.50, 'fatorDesgaste': 1.0, 'gaiola': '23', 'forma': 'Oval'},
    {'luzPadrao': 2.30, 'profundidadeCanalPadrao': 5.20, 'alturaPadrao': 12.70, 'fatorDesgaste': 1.0, 'gaiola': '24', 'forma': 'Redondo'},
    {'luzPadrao': 1.30, 'profundidadeCanalPadrao':3.40, 'alturaPadrao': 8.10, 'fatorDesgaste': 1.0, 'gaiola': '25', 'forma': 'Oval'},
    {'luzPadrao': 1.80, 'profundidadeCanalPadrao': 4.20, 'alturaPadrao': 10.20, 'fatorDesgaste': 1.0, 'gaiola': '26', 'forma': 'Redondo'},
    {'luzPadrao': 1.82, 'profundidadeCanalPadrao': 2.30, 'alturaPadrao': 6.42, 'fatorDesgaste': 1.00, 'gaiola': '27', 'forma': 'Oval'},
    {'luzPadrao': 0.85, 'profundidadeCanalPadrao': 3.65, 'alturaPadrao': 8.15, 'fatorDesgaste': 1.00, 'gaiola': '28', 'forma': 'Redondo'},
    ],
    'CA50 8.0': [
       //desbartador
    {'luzPadrao': 15.0, 'profundidadeCanalPadrao': 47.5, 'alturaPadrao': 110.0, 'fatorDesgaste': 1.0, 'gaiola': '1V', 'forma': 'Retangular'},
    {'luzPadrao': 15.0, 'profundidadeCanalPadrao': 54.0, 'alturaPadrao': 123.0, 'fatorDesgaste': 1.0, 'gaiola': '2H', 'forma': 'Quadrada'},
    {'luzPadrao': 15.0, 'profundidadeCanalPadrao': 34.5, 'alturaPadrao': 84.0, 'fatorDesgaste': 1.0, 'gaiola': '3V', 'forma': 'Oval'},
    {'luzPadrao': 10.0, 'profundidadeCanalPadrao': 45.0, 'alturaPadrao': 100.0, 'fatorDesgaste': 1.0, 'gaiola': '4H', 'forma': 'Redondo'},
    {'luzPadrao': 10.0, 'profundidadeCanalPadrao': 23.0, 'alturaPadrao': 56.0, 'fatorDesgaste': 1.0, 'gaiola': '5V', 'forma': 'Oval'},
    {'luzPadrao': 6.0, 'profundidadeCanalPadrao': 33.0, 'alturaPadrao': 72.0, 'fatorDesgaste': 1.0, 'gaiola': '6H', 'forma': 'Redondo'},
    //intermediario
    {'luzPadrao': 13.0, 'profundidadeCanalPadrao': 15.0, 'alturaPadrao': 43.0, 'fatorDesgaste': 1.0, 'gaiola': '7H', 'forma': 'Oval'},
    {'luzPadrao': 15.0, 'profundidadeCanalPadrao': 20.0, 'alturaPadrao': 55.0, 'fatorDesgaste': 1.0, 'gaiola': '8V', 'forma': 'Redondo'},
    {'luzPadrao': 10.5, 'profundidadeCanalPadrao': 11.0, 'alturaPadrao': 32.5, 'fatorDesgaste': 1.0, 'gaiola': '9H', 'forma': 'Oval'},
    {'luzPadrao': 13.0, 'profundidadeCanalPadrao': 15.0, 'alturaPadrao': 43.0, 'fatorDesgaste': 1.0, 'gaiola': '10V', 'forma': 'Redondo'},
    {'luzPadrao': 12.0, 'profundidadeCanalPadrao': 6.5, 'alturaPadrao': 25.0, 'fatorDesgaste': 1.0, 'gaiola': '11H', 'forma': 'Oval'},
    {'luzPadrao': 9.0, 'profundidadeCanalPadrao': 12.5, 'alturaPadrao': 34.0, 'fatorDesgaste': 1.0, 'gaiola': '12V', 'forma': 'Redondo'},
    //pre-acabado
    {'luzPadrao': 8.70, 'profundidadeCanalPadrao': 7.0, 'alturaPadrao': 22.70, 'fatorDesgaste': 1.0, 'gaiola': '13H', 'forma': 'Oval'},
    {'luzPadrao': 5.00, 'profundidadeCanalPadrao': 11.50, 'alturaPadrao': 28.00, 'fatorDesgaste': 1.0, 'gaiola': '14V', 'forma': 'Redondo'},
    {'luzPadrao': 0.00, 'profundidadeCanalPadrao': 0.00, 'alturaPadrao': 0.00, 'fatorDesgaste': 0.00, 'gaiola': 'DUMMY', 'forma': 'DUMMY'},
    {'luzPadrao': 7.70, 'profundidadeCanalPadrao': 5.40, 'alturaPadrao': 18.50, 'fatorDesgaste': 1.0, 'gaiola': '17H', 'forma': 'Oval'},
    {'luzPadrao': 0.00, 'profundidadeCanalPadrao': 0.00, 'alturaPadrao': 0.00, 'fatorDesgaste': 0.0, 'gaiola': 'DUMMY', 'forma': 'DUMMY'},
    {'luzPadrao': 4.00, 'profundidadeCanalPadrao': 9.75, 'alturaPadrao': 23.50, 'fatorDesgaste': 1.0, 'gaiola': '18V', 'forma': 'Redondo'},
     //bloco
    {'luzPadrao': 5.50, 'profundidadeCanalPadrao': 4.55, 'alturaPadrao': 14.60, 'fatorDesgaste': 1.0, 'gaiola': '17', 'forma': 'Oval'},
    {'luzPadrao': 3.50, 'profundidadeCanalPadrao': 7.90, 'alturaPadrao': 19.30, 'fatorDesgaste': 1.0, 'gaiola': '18', 'forma': 'Redondo'},
    {'luzPadrao': 1.45, 'profundidadeCanalPadrao': 5.60, 'alturaPadrao': 12.65, 'fatorDesgaste': 1.0, 'gaiola': '21', 'forma': 'Oval'},
    {'luzPadrao': 1.10, 'profundidadeCanalPadrao': 7.00, 'alturaPadrao': 15.10, 'fatorDesgaste': 1.0, 'gaiola': '22', 'forma': 'Redondo'},
    {'luzPadrao': 0.70, 'profundidadeCanalPadrao': 4.60, 'alturaPadrao': 9.90, 'fatorDesgaste': 1.0, 'gaiola': '23', 'forma': 'Oval'},
    {'luzPadrao': 1.60, 'profundidadeCanalPadrao': 5.20, 'alturaPadrao': 12.00, 'fatorDesgaste': 1.0, 'gaiola': '24', 'forma': 'Redondo'},
    {'luzPadrao': 0.85, 'profundidadeCanalPadrao':3.40, 'alturaPadrao': 7.65, 'fatorDesgaste': 1.0, 'gaiola': '25', 'forma': 'Oval'},
    {'luzPadrao': 1.40, 'profundidadeCanalPadrao': 4.20, 'alturaPadrao': 9.80, 'fatorDesgaste': 1.0, 'gaiola': '26', 'forma': 'Redondo'},
    {'luzPadrao': 1.20, 'profundidadeCanalPadrao': 2.30, 'alturaPadrao': 5.80, 'fatorDesgaste': 1.00, 'gaiola': '27', 'forma': 'Oval'},
    {'luzPadrao': 1.22, 'profundidadeCanalPadrao': 3.14, 'alturaPadrao': 7.50, 'fatorDesgaste': 1.00, 'gaiola': '28', 'forma': 'Redondo'},
    ],
    'FM 10.0': [
       //desbartador
    {'luzPadrao': 15.0, 'profundidadeCanalPadrao': 47.5, 'alturaPadrao': 110.0, 'fatorDesgaste': 1.0, 'gaiola': '1V', 'forma': 'Retangular'},
    {'luzPadrao': 15.0, 'profundidadeCanalPadrao': 54.0, 'alturaPadrao': 123.0, 'fatorDesgaste': 1.0, 'gaiola': '2H', 'forma': 'Quadrada'},
    {'luzPadrao': 15.0, 'profundidadeCanalPadrao': 34.5, 'alturaPadrao': 84.0, 'fatorDesgaste': 1.0, 'gaiola': '3V', 'forma': 'Oval'},
    {'luzPadrao': 10.0, 'profundidadeCanalPadrao': 45.0, 'alturaPadrao': 100.0, 'fatorDesgaste': 1.0, 'gaiola': '4H', 'forma': 'Redondo'},
    {'luzPadrao': 10.0, 'profundidadeCanalPadrao': 23.0, 'alturaPadrao': 56.0, 'fatorDesgaste': 1.0, 'gaiola': '5V', 'forma': 'Oval'},
    {'luzPadrao': 6.0, 'profundidadeCanalPadrao': 33.0, 'alturaPadrao': 72.0, 'fatorDesgaste': 1.0, 'gaiola': '6H', 'forma': 'Redondo'},
    //intermediario
    {'luzPadrao': 13.0, 'profundidadeCanalPadrao': 15.0, 'alturaPadrao': 43.0, 'fatorDesgaste': 1.0, 'gaiola': '7H', 'forma': 'Oval'},
    {'luzPadrao': 15.0, 'profundidadeCanalPadrao': 20.0, 'alturaPadrao': 55.0, 'fatorDesgaste': 1.0, 'gaiola': '8V', 'forma': 'Redondo'},
    {'luzPadrao': 10.5, 'profundidadeCanalPadrao': 11.0, 'alturaPadrao': 32.5, 'fatorDesgaste': 1.0, 'gaiola': '9H', 'forma': 'Oval'},
    {'luzPadrao': 13.0, 'profundidadeCanalPadrao': 15.0, 'alturaPadrao': 43.0, 'fatorDesgaste': 1.0, 'gaiola': '10V', 'forma': 'Redondo'},
    {'luzPadrao': 12.0, 'profundidadeCanalPadrao': 6.5, 'alturaPadrao': 25.0, 'fatorDesgaste': 1.0, 'gaiola': '11H', 'forma': 'Oval'},
    {'luzPadrao': 9.0, 'profundidadeCanalPadrao': 12.5, 'alturaPadrao': 34.0, 'fatorDesgaste': 1.0, 'gaiola': '12V', 'forma': 'Redondo'},
    //pre-acabado
    {'luzPadrao': 9.60, 'profundidadeCanalPadrao': 7.0, 'alturaPadrao': 23.60, 'fatorDesgaste': 1.0, 'gaiola': '13H', 'forma': 'Oval'},
    {'luzPadrao': 5.70, 'profundidadeCanalPadrao': 11.50, 'alturaPadrao': 28.70, 'fatorDesgaste': 1.0, 'gaiola': '14V', 'forma': 'Redondo'},
    {'luzPadrao': 0.00, 'profundidadeCanalPadrao': 0.00, 'alturaPadrao': 0.00, 'fatorDesgaste': 0.00, 'gaiola': 'DUMMY', 'forma': 'DUMMY'},
    {'luzPadrao': 8.00, 'profundidadeCanalPadrao': 5.40, 'alturaPadrao': 18.80, 'fatorDesgaste': 1.0, 'gaiola': '17H', 'forma': 'Oval'},
    {'luzPadrao': 0.00, 'profundidadeCanalPadrao': 0.00, 'alturaPadrao': 0.00, 'fatorDesgaste': 0.0, 'gaiola': 'DUMMY', 'forma': 'DUMMY'},
    {'luzPadrao': 4.50, 'profundidadeCanalPadrao': 9.75, 'alturaPadrao': 24.00, 'fatorDesgaste': 1.0, 'gaiola': '18V', 'forma': 'Redondo'},
     //bloco
    {'luzPadrao': 5.70, 'profundidadeCanalPadrao': 4.55, 'alturaPadrao': 14.80, 'fatorDesgaste': 1.0, 'gaiola': '17', 'forma': 'Oval'},
    {'luzPadrao': 3.65, 'profundidadeCanalPadrao': 7.90, 'alturaPadrao': 19.45, 'fatorDesgaste': 1.0, 'gaiola': '18', 'forma': 'Redondo'},
    {'luzPadrao': 2.10, 'profundidadeCanalPadrao': 5.60, 'alturaPadrao': 13.30, 'fatorDesgaste': 1.0, 'gaiola': '21', 'forma': 'Oval'},
    {'luzPadrao': 2.00, 'profundidadeCanalPadrao': 7.00, 'alturaPadrao': 16.00, 'fatorDesgaste': 1.0, 'gaiola': '22', 'forma': 'Redondo'},
    {'luzPadrao': 1.40, 'profundidadeCanalPadrao': 4.60, 'alturaPadrao': 10.60, 'fatorDesgaste': 1.0, 'gaiola': '23', 'forma': 'Oval'},
    {'luzPadrao': 2.35, 'profundidadeCanalPadrao': 5.20, 'alturaPadrao': 12.75, 'fatorDesgaste': 1.0, 'gaiola': '24', 'forma': 'Redondo'},
    {'luzPadrao': 1.50, 'profundidadeCanalPadrao':3.40, 'alturaPadrao': 8.30, 'fatorDesgaste': 1.0, 'gaiola': '25', 'forma': 'Oval'},
    {'luzPadrao': 1.20, 'profundidadeCanalPadrao': 4.50, 'alturaPadrao': 10.20, 'fatorDesgaste': 1.0, 'gaiola': '26', 'forma': 'Redondo'},
    {'luzPadrao': 0.00, 'profundidadeCanalPadrao': 0.00, 'alturaPadrao': 0.00, 'fatorDesgaste': 0.00, 'gaiola': 'DUMMY', 'forma': 'DUMMY'},
    {'luzPadrao': 0.00, 'profundidadeCanalPadrao': 0.00, 'alturaPadrao': 0.00, 'fatorDesgaste': 0.00, 'gaiola': 'DUMMY', 'forma': 'DUMMY'},
    ],
    'CA50 10.0': [
       //desbartador
    {'luzPadrao': 15.0, 'profundidadeCanalPadrao': 47.5, 'alturaPadrao': 110.0, 'fatorDesgaste': 1.0, 'gaiola': '1V', 'forma': 'Retangular'},
    {'luzPadrao': 15.0, 'profundidadeCanalPadrao': 54.0, 'alturaPadrao': 123.0, 'fatorDesgaste': 1.0, 'gaiola': '2H', 'forma': 'Quadrada'},
    {'luzPadrao': 15.0, 'profundidadeCanalPadrao': 34.5, 'alturaPadrao': 84.0, 'fatorDesgaste': 1.0, 'gaiola': '3V', 'forma': 'Oval'},
    {'luzPadrao': 10.0, 'profundidadeCanalPadrao': 45.0, 'alturaPadrao': 100.0, 'fatorDesgaste': 1.0, 'gaiola': '4H', 'forma': 'Redondo'},
    {'luzPadrao': 10.0, 'profundidadeCanalPadrao': 23.0, 'alturaPadrao': 56.0, 'fatorDesgaste': 1.0, 'gaiola': '5V', 'forma': 'Oval'},
    {'luzPadrao': 6.0, 'profundidadeCanalPadrao': 33.0, 'alturaPadrao': 72.0, 'fatorDesgaste': 1.0, 'gaiola': '6H', 'forma': 'Redondo'},
    //intermediario
    {'luzPadrao': 13.0, 'profundidadeCanalPadrao': 15.0, 'alturaPadrao': 43.0, 'fatorDesgaste': 1.0, 'gaiola': '7H', 'forma': 'Oval'},
    {'luzPadrao': 15.0, 'profundidadeCanalPadrao': 20.0, 'alturaPadrao': 55.0, 'fatorDesgaste': 1.0, 'gaiola': '8V', 'forma': 'Redondo'},
    {'luzPadrao': 10.5, 'profundidadeCanalPadrao': 11.0, 'alturaPadrao': 32.5, 'fatorDesgaste': 1.0, 'gaiola': '9H', 'forma': 'Oval'},
    {'luzPadrao': 13.0, 'profundidadeCanalPadrao': 15.0, 'alturaPadrao': 43.0, 'fatorDesgaste': 1.0, 'gaiola': '10V', 'forma': 'Redondo'},
    {'luzPadrao': 12.0, 'profundidadeCanalPadrao': 6.5, 'alturaPadrao': 25.0, 'fatorDesgaste': 1.0, 'gaiola': '11H', 'forma': 'Oval'},
    {'luzPadrao': 9.0, 'profundidadeCanalPadrao': 12.5, 'alturaPadrao': 34.0, 'fatorDesgaste': 1.0, 'gaiola': '12V', 'forma': 'Redondo'},
    //pre-acabado
    {'luzPadrao': 8.60, 'profundidadeCanalPadrao': 7.0, 'alturaPadrao': 22.60, 'fatorDesgaste': 1.0, 'gaiola': '13H', 'forma': 'Oval'},
    {'luzPadrao': 5.00, 'profundidadeCanalPadrao': 11.50, 'alturaPadrao': 28.00, 'fatorDesgaste': 1.0, 'gaiola': '14V', 'forma': 'Redondo'},
    {'luzPadrao': 0.00, 'profundidadeCanalPadrao': 0.00, 'alturaPadrao': 0.00, 'fatorDesgaste': 0.00, 'gaiola': 'DUMMY', 'forma': 'DUMMY'},
    {'luzPadrao': 8.10, 'profundidadeCanalPadrao': 5.40, 'alturaPadrao': 18.90, 'fatorDesgaste': 1.0, 'gaiola': '17H', 'forma': 'Oval'},
    {'luzPadrao': 0.00, 'profundidadeCanalPadrao': 0.00, 'alturaPadrao': 0.00, 'fatorDesgaste': 0.0, 'gaiola': 'DUMMY', 'forma': 'DUMMY'},
    {'luzPadrao': 4.40, 'profundidadeCanalPadrao': 9.75, 'alturaPadrao': 23.90, 'fatorDesgaste': 1.0, 'gaiola': '18V', 'forma': 'Redondo'},
     //bloco
    {'luzPadrao': 5.50, 'profundidadeCanalPadrao': 4.55, 'alturaPadrao': 14.60, 'fatorDesgaste': 1.0, 'gaiola': '17', 'forma': 'Oval'},
    {'luzPadrao': 3.50, 'profundidadeCanalPadrao': 7.90, 'alturaPadrao': 19.30, 'fatorDesgaste': 1.0, 'gaiola': '18', 'forma': 'Redondo'},
    {'luzPadrao': 1.30, 'profundidadeCanalPadrao': 5.60, 'alturaPadrao': 12.50, 'fatorDesgaste': 1.0, 'gaiola': '21', 'forma': 'Oval'},
    {'luzPadrao': 1.10, 'profundidadeCanalPadrao': 7.00, 'alturaPadrao': 15.10, 'fatorDesgaste': 1.0, 'gaiola': '22', 'forma': 'Redondo'},
    {'luzPadrao': 0.70, 'profundidadeCanalPadrao': 4.60, 'alturaPadrao': 9.90, 'fatorDesgaste': 1.0, 'gaiola': '23', 'forma': 'Oval'},
    {'luzPadrao': 1.60, 'profundidadeCanalPadrao': 5.20, 'alturaPadrao': 12.00, 'fatorDesgaste': 1.0, 'gaiola': '24', 'forma': 'Redondo'},
    {'luzPadrao': 0.85, 'profundidadeCanalPadrao':3.40, 'alturaPadrao': 7.65, 'fatorDesgaste': 1.0, 'gaiola': '25', 'forma': 'Oval'},
    {'luzPadrao': 1.35, 'profundidadeCanalPadrao': 3.95, 'alturaPadrao': 9.80, 'fatorDesgaste': 1.0, 'gaiola': '26', 'forma': 'Redondo'},
    {'luzPadrao': 0.00, 'profundidadeCanalPadrao': 0.00, 'alturaPadrao': 0.00, 'fatorDesgaste': 1.00, 'gaiola': 'DUMMY', 'forma': 'DUMMY'},
    {'luzPadrao': 0.00, 'profundidadeCanalPadrao': 0.00, 'alturaPadrao': 0.00, 'fatorDesgaste': 1.00, 'gaiola': 'DUMMY', 'forma': 'DUMMY'},
    ],
    'FM 12.5': [
       //desbartador
    {'luzPadrao': 15.0, 'profundidadeCanalPadrao': 47.5, 'alturaPadrao': 110.0, 'fatorDesgaste': 1.0, 'gaiola': '1V', 'forma': 'Retangular'},
    {'luzPadrao': 15.0, 'profundidadeCanalPadrao': 54.0, 'alturaPadrao': 123.0, 'fatorDesgaste': 1.0, 'gaiola': '2H', 'forma': 'Quadrada'},
    {'luzPadrao': 15.0, 'profundidadeCanalPadrao': 34.5, 'alturaPadrao': 84.0, 'fatorDesgaste': 1.0, 'gaiola': '3V', 'forma': 'Oval'},
    {'luzPadrao': 10.0, 'profundidadeCanalPadrao': 45.0, 'alturaPadrao': 100.0, 'fatorDesgaste': 1.0, 'gaiola': '4H', 'forma': 'Redondo'},
    {'luzPadrao': 10.0, 'profundidadeCanalPadrao': 23.0, 'alturaPadrao': 56.0, 'fatorDesgaste': 1.0, 'gaiola': '5V', 'forma': 'Oval'},
    {'luzPadrao': 6.0, 'profundidadeCanalPadrao': 33.0, 'alturaPadrao': 72.0, 'fatorDesgaste': 1.0, 'gaiola': '6H', 'forma': 'Redondo'},
    //intermediario
    {'luzPadrao': 13.0, 'profundidadeCanalPadrao': 15.0, 'alturaPadrao': 43.0, 'fatorDesgaste': 1.0, 'gaiola': '7H', 'forma': 'Oval'},
    {'luzPadrao': 15.0, 'profundidadeCanalPadrao': 20.0, 'alturaPadrao': 55.0, 'fatorDesgaste': 1.0, 'gaiola': '8V', 'forma': 'Redondo'},
    {'luzPadrao': 10.5, 'profundidadeCanalPadrao': 11.0, 'alturaPadrao': 32.5, 'fatorDesgaste': 1.0, 'gaiola': '9H', 'forma': 'Oval'},
    {'luzPadrao': 13.0, 'profundidadeCanalPadrao': 15.0, 'alturaPadrao': 43.0, 'fatorDesgaste': 1.0, 'gaiola': '10V', 'forma': 'Redondo'},
    {'luzPadrao': 12.0, 'profundidadeCanalPadrao': 6.5, 'alturaPadrao': 25.0, 'fatorDesgaste': 1.0, 'gaiola': '11H', 'forma': 'Oval'},
    {'luzPadrao': 9.0, 'profundidadeCanalPadrao': 12.5, 'alturaPadrao': 34.0, 'fatorDesgaste': 1.0, 'gaiola': '12V', 'forma': 'Redondo'},
    //pre-acabado
    {'luzPadrao': 8.60, 'profundidadeCanalPadrao': 7.0, 'alturaPadrao': 22.60, 'fatorDesgaste': 1.0, 'gaiola': '13H', 'forma': 'Oval'},
    {'luzPadrao': 4.90, 'profundidadeCanalPadrao': 11.50, 'alturaPadrao': 27.90, 'fatorDesgaste': 1.0, 'gaiola': '14V', 'forma': 'Redondo'},
    {'luzPadrao': 0.00, 'profundidadeCanalPadrao': 0.00, 'alturaPadrao': 0.00, 'fatorDesgaste': 0.00, 'gaiola': 'DUMMY', 'forma': 'DUMMY'},
    {'luzPadrao': 7.90, 'profundidadeCanalPadrao': 5.40, 'alturaPadrao': 18.70, 'fatorDesgaste': 1.0, 'gaiola': '15H', 'forma': 'Oval'},
    {'luzPadrao': 0.00, 'profundidadeCanalPadrao': 0.00, 'alturaPadrao': 0.00, 'fatorDesgaste': 0.0, 'gaiola': 'DUMMY', 'forma': 'DUMMY'},
    {'luzPadrao': 4.10, 'profundidadeCanalPadrao': 9.75, 'alturaPadrao': 23.60, 'fatorDesgaste': 1.0, 'gaiola': '16V', 'forma': 'Redondo'},
     //bloco
    {'luzPadrao': 5.40, 'profundidadeCanalPadrao': 4.55, 'alturaPadrao': 14.50, 'fatorDesgaste': 1.0, 'gaiola': '17', 'forma': 'Oval'},
    {'luzPadrao': 3.50, 'profundidadeCanalPadrao': 7.90, 'alturaPadrao': 19.30, 'fatorDesgaste': 1.0, 'gaiola': '18', 'forma': 'Redondo'},
    {'luzPadrao': 1.35, 'profundidadeCanalPadrao': 5.60, 'alturaPadrao': 12.55, 'fatorDesgaste': 1.0, 'gaiola': '21', 'forma': 'Oval'},
    {'luzPadrao': 1.10, 'profundidadeCanalPadrao': 7.00, 'alturaPadrao': 15.10, 'fatorDesgaste': 1.0, 'gaiola': '22', 'forma': 'Redondo'},
    {'luzPadrao': 1.10, 'profundidadeCanalPadrao': 4.60, 'alturaPadrao': 10.30, 'fatorDesgaste': 1.0, 'gaiola': '23', 'forma': 'Oval'},
    {'luzPadrao': 1.45, 'profundidadeCanalPadrao': 5.10, 'alturaPadrao': 11.65, 'fatorDesgaste': 1.0, 'gaiola': '24', 'forma': 'Redondo'},
    {'luzPadrao': 0.00, 'profundidadeCanalPadrao':0.00, 'alturaPadrao': 0.00, 'fatorDesgaste': 1.0, 'gaiola': 'DUMMY', 'DUMMY': 'DUMMY'},
    {'luzPadrao': 0.00, 'profundidadeCanalPadrao': 0.00, 'alturaPadrao': 0.00, 'fatorDesgaste': 1.0, 'gaiola': 'DUMMY', 'DUMMY': 'DUMMY'},
    {'luzPadrao': 0.00, 'profundidadeCanalPadrao': 0.00, 'alturaPadrao': 0.00, 'fatorDesgaste': 0.00, 'gaiola': 'DUMMY', 'DUMMY': 'DUMMY'},
    {'luzPadrao': 0.00, 'profundidadeCanalPadrao': 0.00, 'alturaPadrao': 0.00, 'fatorDesgaste': 0.00, 'gaiola': 'DUMMY', 'DUMMY': 'DUMMY'},
    ],
    'CA50 12.5': [
       //desbartador
    {'luzPadrao': 15.0, 'profundidadeCanalPadrao': 47.5, 'alturaPadrao': 110.0, 'fatorDesgaste': 1.0, 'gaiola': '1V', 'forma': 'Retangular'},
    {'luzPadrao': 15.0, 'profundidadeCanalPadrao': 54.0, 'alturaPadrao': 123.0, 'fatorDesgaste': 1.0, 'gaiola': '2H', 'forma': 'Quadrada'},
    {'luzPadrao': 15.0, 'profundidadeCanalPadrao': 34.5, 'alturaPadrao': 84.0, 'fatorDesgaste': 1.0, 'gaiola': '3V', 'forma': 'Oval'},
    {'luzPadrao': 10.0, 'profundidadeCanalPadrao': 45.0, 'alturaPadrao': 100.0, 'fatorDesgaste': 1.0, 'gaiola': '4H', 'forma': 'Redondo'},
    {'luzPadrao': 10.0, 'profundidadeCanalPadrao': 23.0, 'alturaPadrao': 56.0, 'fatorDesgaste': 1.0, 'gaiola': '5V', 'forma': 'Oval'},
    {'luzPadrao': 6.0, 'profundidadeCanalPadrao': 33.0, 'alturaPadrao': 72.0, 'fatorDesgaste': 1.0, 'gaiola': '6H', 'forma': 'Redondo'},
    //intermediario
    {'luzPadrao': 13.0, 'profundidadeCanalPadrao': 15.0, 'alturaPadrao': 43.0, 'fatorDesgaste': 1.0, 'gaiola': '7H', 'forma': 'Oval'},
    {'luzPadrao': 15.0, 'profundidadeCanalPadrao': 20.0, 'alturaPadrao': 55.0, 'fatorDesgaste': 1.0, 'gaiola': '8V', 'forma': 'Redondo'},
    {'luzPadrao': 10.5, 'profundidadeCanalPadrao': 11.0, 'alturaPadrao': 32.5, 'fatorDesgaste': 1.0, 'gaiola': '9H', 'forma': 'Oval'},
    {'luzPadrao': 13.0, 'profundidadeCanalPadrao': 15.0, 'alturaPadrao': 43.0, 'fatorDesgaste': 1.0, 'gaiola': '10V', 'forma': 'Redondo'},
    {'luzPadrao': 12.0, 'profundidadeCanalPadrao': 6.5, 'alturaPadrao': 25.0, 'fatorDesgaste': 1.0, 'gaiola': '11H', 'forma': 'Oval'},
    {'luzPadrao': 9.0, 'profundidadeCanalPadrao': 12.5, 'alturaPadrao': 34.0, 'fatorDesgaste': 1.0, 'gaiola': '12V', 'forma': 'Redondo'},
    //pre-acabado
    {'luzPadrao': 9.60, 'profundidadeCanalPadrao': 7.0, 'alturaPadrao': 23.60, 'fatorDesgaste': 1.0, 'gaiola': '13H', 'forma': 'Oval'},
    {'luzPadrao': 5.70, 'profundidadeCanalPadrao': 11.50, 'alturaPadrao': 28.70, 'fatorDesgaste': 1.0, 'gaiola': '14V', 'forma': 'Redondo'},
    {'luzPadrao': 0.00, 'profundidadeCanalPadrao': 0.00, 'alturaPadrao': 0.00, 'fatorDesgaste': 0.00, 'gaiola': 'DUMMY', 'forma': 'DUMMY'},
    {'luzPadrao': 8.60, 'profundidadeCanalPadrao': 5.40, 'alturaPadrao': 19.40, 'fatorDesgaste': 1.0, 'gaiola': '15H', 'forma': 'Oval'},
    {'luzPadrao': 0.00, 'profundidadeCanalPadrao': 0.00, 'alturaPadrao': 0.00, 'fatorDesgaste': 0.0, 'gaiola': 'DUMMY', 'forma': 'DUMMY'},
    {'luzPadrao': 4.50, 'profundidadeCanalPadrao': 9.75, 'alturaPadrao': 24.25, 'fatorDesgaste': 1.0, 'gaiola': '16V', 'forma': 'Redondo'},
     //bloco
    {'luzPadrao': 5.40, 'profundidadeCanalPadrao': 4.55, 'alturaPadrao': 14.50, 'fatorDesgaste': 1.0, 'gaiola': '17', 'forma': 'Oval'},
    {'luzPadrao': 3.50, 'profundidadeCanalPadrao': 7.90, 'alturaPadrao': 19.30, 'fatorDesgaste': 1.0, 'gaiola': '18', 'forma': 'Redondo'},
    {'luzPadrao': 1.60, 'profundidadeCanalPadrao': 5.60, 'alturaPadrao': 12.80, 'fatorDesgaste': 1.0, 'gaiola': '21', 'forma': 'Oval'},
    {'luzPadrao': 1.60, 'profundidadeCanalPadrao': 7.00, 'alturaPadrao': 15.60, 'fatorDesgaste': 1.0, 'gaiola': '22', 'forma': 'Redondo'},
    {'luzPadrao': 1.20, 'profundidadeCanalPadrao': 4.60, 'alturaPadrao': 10.40, 'fatorDesgaste': 1.0, 'gaiola': '23', 'forma': 'Oval'},
    {'luzPadrao': 0.80, 'profundidadeCanalPadrao': 5.94, 'alturaPadrao': 12.68, 'fatorDesgaste': 1.0, 'gaiola': '24', 'forma': 'Redondo'},
    {'luzPadrao': 0.00, 'profundidadeCanalPadrao':0.00, 'alturaPadrao': 0.00, 'fatorDesgaste': 1.0, 'gaiola': 'DUMMY', 'DUMMY': 'DUMMY'},
    {'luzPadrao': 0.00, 'profundidadeCanalPadrao': 0.00, 'alturaPadrao': 0.00, 'fatorDesgaste': 1.0, 'gaiola': 'DUMMY', 'DUMMY': 'DUMMY'},
    {'luzPadrao': 0.00, 'profundidadeCanalPadrao': 0.00, 'alturaPadrao': 0.00, 'fatorDesgaste': 0.00, 'gaiola': 'DUMMY', 'DUMMY': 'DUMMY'},
    {'luzPadrao': 0.00, 'profundidadeCanalPadrao': 0.00, 'alturaPadrao': 0.00, 'fatorDesgaste': 0.00, 'gaiola': 'DUMMY', 'DUMMY': 'DUMMY'},
    ],
    'FM 16.0': [
       //desbartador
    {'luzPadrao': 15.0, 'profundidadeCanalPadrao': 47.5, 'alturaPadrao': 110.0, 'fatorDesgaste': 1.0, 'gaiola': '1V', 'forma': 'Retangular'},
    {'luzPadrao': 15.0, 'profundidadeCanalPadrao': 54.0, 'alturaPadrao': 123.0, 'fatorDesgaste': 1.0, 'gaiola': '2H', 'forma': 'Quadrada'},
    {'luzPadrao': 15.0, 'profundidadeCanalPadrao': 34.5, 'alturaPadrao': 84.0, 'fatorDesgaste': 1.0, 'gaiola': '3V', 'forma': 'Oval'},
    {'luzPadrao': 10.0, 'profundidadeCanalPadrao': 45.0, 'alturaPadrao': 100.0, 'fatorDesgaste': 1.0, 'gaiola': '4H', 'forma': 'Redondo'},
    {'luzPadrao': 10.0, 'profundidadeCanalPadrao': 23.0, 'alturaPadrao': 56.0, 'fatorDesgaste': 1.0, 'gaiola': '5V', 'forma': 'Oval'},
    {'luzPadrao': 6.0, 'profundidadeCanalPadrao': 33.0, 'alturaPadrao': 72.0, 'fatorDesgaste': 1.0, 'gaiola': '6H', 'forma': 'Redondo'},
    //intermediario
    {'luzPadrao': 13.0, 'profundidadeCanalPadrao': 15.0, 'alturaPadrao': 43.0, 'fatorDesgaste': 1.0, 'gaiola': '7H', 'forma': 'Oval'},
    {'luzPadrao': 15.0, 'profundidadeCanalPadrao': 20.0, 'alturaPadrao': 55.0, 'fatorDesgaste': 1.0, 'gaiola': '8V', 'forma': 'Redondo'},
    {'luzPadrao': 10.5, 'profundidadeCanalPadrao': 11.0, 'alturaPadrao': 32.5, 'fatorDesgaste': 1.0, 'gaiola': '9H', 'forma': 'Oval'},
    {'luzPadrao': 13.0, 'profundidadeCanalPadrao': 15.0, 'alturaPadrao': 43.0, 'fatorDesgaste': 1.0, 'gaiola': '10V', 'forma': 'Redondo'},
    {'luzPadrao': 12.0, 'profundidadeCanalPadrao': 6.5, 'alturaPadrao': 25.0, 'fatorDesgaste': 1.0, 'gaiola': '11H', 'forma': 'Oval'},
    {'luzPadrao': 9.0, 'profundidadeCanalPadrao': 12.5, 'alturaPadrao': 34.0, 'fatorDesgaste': 1.0, 'gaiola': '12V', 'forma': 'Redondo'},
    //pre-acabado
    {'luzPadrao': 9.60, 'profundidadeCanalPadrao': 7.0, 'alturaPadrao': 23.60, 'fatorDesgaste': 1.0, 'gaiola': '13H', 'forma': 'Oval'},
    {'luzPadrao': 6.00, 'profundidadeCanalPadrao': 11.50, 'alturaPadrao': 29.00, 'fatorDesgaste': 1.0, 'gaiola': '14V', 'forma': 'Redondo'},
    {'luzPadrao': 0.00, 'profundidadeCanalPadrao': 0.00, 'alturaPadrao': 0.00, 'fatorDesgaste': 0.00, 'gaiola': 'DUMMY', 'forma': 'DUMMY'},
    {'luzPadrao': 0.00, 'profundidadeCanalPadrao': 0.00, 'alturaPadrao': 0.00, 'fatorDesgaste': 0.00, 'gaiola': 'DUMMY', 'forma': 'DUMMY'},
    {'luzPadrao': 9.00, 'profundidadeCanalPadrao': 5.40, 'alturaPadrao': 19.80, 'fatorDesgaste': 1.0, 'gaiola': '15H', 'forma': 'Oval'},
    {'luzPadrao': 5.60, 'profundidadeCanalPadrao': 9.75, 'alturaPadrao': 25.10, 'fatorDesgaste': 1.0, 'gaiola': '16V', 'forma': 'Redondo'},
     //bloco
    {'luzPadrao': 6.00, 'profundidadeCanalPadrao': 4.55, 'alturaPadrao': 15.10, 'fatorDesgaste': 1.0, 'gaiola': '17', 'forma': 'Oval'},
    {'luzPadrao': 4.30, 'profundidadeCanalPadrao': 7.90, 'alturaPadrao': 20.10, 'fatorDesgaste': 1.0, 'gaiola': '18', 'forma': 'Redondo'},
    {'luzPadrao': 1.05, 'profundidadeCanalPadrao': 5.60, 'alturaPadrao': 12.25, 'fatorDesgaste': 1.0, 'gaiola': '21', 'forma': 'Oval'},
    {'luzPadrao': 1.30, 'profundidadeCanalPadrao': 7.40, 'alturaPadrao': 16.10, 'fatorDesgaste': 1.0, 'gaiola': '22', 'forma': 'Redondo'},
    {'luzPadrao': 0.00, 'profundidadeCanalPadrao': 0.00, 'alturaPadrao': 0.00, 'fatorDesgaste': 1.0, 'gaiola': 'DUMMY', 'forma': 'DUMMY'},
    {'luzPadrao': 0.00, 'profundidadeCanalPadrao': 0.00, 'alturaPadrao': 0.00, 'fatorDesgaste': 1.0, 'gaiola': 'DUMMY', 'forma': 'DUMMY'},
    {'luzPadrao': 0.00, 'profundidadeCanalPadrao': 0.00, 'alturaPadrao': 0.00, 'fatorDesgaste': 1.0, 'gaiola': 'DUMMY', 'DUMMY': 'DUMMY'},
    {'luzPadrao': 0.00, 'profundidadeCanalPadrao': 0.00, 'alturaPadrao': 0.00, 'fatorDesgaste': 1.0, 'gaiola': 'DUMMY', 'DUMMY': 'DUMMY'},
    {'luzPadrao': 0.00, 'profundidadeCanalPadrao': 0.00, 'alturaPadrao': 0.00, 'fatorDesgaste': 0.00, 'gaiola': 'DUMMY', 'DUMMY': 'DUMMY'},
    {'luzPadrao': 0.00, 'profundidadeCanalPadrao': 0.00, 'alturaPadrao': 0.00, 'fatorDesgaste': 0.00, 'gaiola': 'DUMMY', 'DUMMY': 'DUMMY'},
    ],
    'CA50 16.0': [
       //desbartador
    {'luzPadrao': 15.0, 'profundidadeCanalPadrao': 47.5, 'alturaPadrao': 110.0, 'fatorDesgaste': 1.0, 'gaiola': '1V', 'forma': 'Retangular'},
    {'luzPadrao': 15.0, 'profundidadeCanalPadrao': 54.0, 'alturaPadrao': 123.0, 'fatorDesgaste': 1.0, 'gaiola': '2H', 'forma': 'Quadrada'},
    {'luzPadrao': 15.0, 'profundidadeCanalPadrao': 34.5, 'alturaPadrao': 84.0, 'fatorDesgaste': 1.0, 'gaiola': '3V', 'forma': 'Oval'},
    {'luzPadrao': 10.0, 'profundidadeCanalPadrao': 45.0, 'alturaPadrao': 100.0, 'fatorDesgaste': 1.0, 'gaiola': '4H', 'forma': 'Redondo'},
    {'luzPadrao': 10.0, 'profundidadeCanalPadrao': 23.0, 'alturaPadrao': 56.0, 'fatorDesgaste': 1.0, 'gaiola': '5V', 'forma': 'Oval'},
    {'luzPadrao': 6.0, 'profundidadeCanalPadrao': 33.0, 'alturaPadrao': 72.0, 'fatorDesgaste': 1.0, 'gaiola': '6H', 'forma': 'Redondo'},
    //intermediario
    {'luzPadrao': 13.0, 'profundidadeCanalPadrao': 15.0, 'alturaPadrao': 43.0, 'fatorDesgaste': 1.0, 'gaiola': '7H', 'forma': 'Oval'},
    {'luzPadrao': 15.0, 'profundidadeCanalPadrao': 20.0, 'alturaPadrao': 55.0, 'fatorDesgaste': 1.0, 'gaiola': '8V', 'forma': 'Redondo'},
    {'luzPadrao': 10.5, 'profundidadeCanalPadrao': 11.0, 'alturaPadrao': 32.5, 'fatorDesgaste': 1.0, 'gaiola': '9H', 'forma': 'Oval'},
    {'luzPadrao': 13.0, 'profundidadeCanalPadrao': 15.0, 'alturaPadrao': 43.0, 'fatorDesgaste': 1.0, 'gaiola': '10V', 'forma': 'Redondo'},
    {'luzPadrao': 12.0, 'profundidadeCanalPadrao': 6.5, 'alturaPadrao': 25.0, 'fatorDesgaste': 1.0, 'gaiola': '11H', 'forma': 'Oval'},
    {'luzPadrao': 9.0, 'profundidadeCanalPadrao': 12.5, 'alturaPadrao': 34.0, 'fatorDesgaste': 1.0, 'gaiola': '12V', 'forma': 'Redondo'},
    //pre-acabado
    {'luzPadrao': 9.50, 'profundidadeCanalPadrao': 7.0, 'alturaPadrao': 23.50, 'fatorDesgaste': 1.0, 'gaiola': '13H', 'forma': 'Oval'},
    {'luzPadrao': 5.80, 'profundidadeCanalPadrao': 11.50, 'alturaPadrao': 28.80, 'fatorDesgaste': 1.0, 'gaiola': '14V', 'forma': 'Redondo'},
    {'luzPadrao': 0.00, 'profundidadeCanalPadrao': 0.00, 'alturaPadrao': 0.00, 'fatorDesgaste': 0.00, 'gaiola': 'DUMMY', 'forma': 'DUMMY'},
    {'luzPadrao': 0.00, 'profundidadeCanalPadrao': 0.00, 'alturaPadrao': 0.00, 'fatorDesgaste': 0.00, 'gaiola': 'DUMMY', 'forma': 'DUMMY'},
    {'luzPadrao': 8.80, 'profundidadeCanalPadrao': 5.40, 'alturaPadrao': 19.60, 'fatorDesgaste': 1.0, 'gaiola': '15H', 'forma': 'Oval'},
    {'luzPadrao': 5.20, 'profundidadeCanalPadrao': 9.75, 'alturaPadrao': 24.70, 'fatorDesgaste': 1.0, 'gaiola': '16V', 'forma': 'Redondo'},
     //bloco
    {'luzPadrao': 5.80, 'profundidadeCanalPadrao': 4.55, 'alturaPadrao': 14.90, 'fatorDesgaste': 1.0, 'gaiola': '17', 'forma': 'Oval'},
    {'luzPadrao': 3.90, 'profundidadeCanalPadrao': 7.90, 'alturaPadrao': 19.70, 'fatorDesgaste': 1.0, 'gaiola': '18', 'forma': 'Redondo'},
    {'luzPadrao': 2.20, 'profundidadeCanalPadrao': 5.60, 'alturaPadrao': 13.40, 'fatorDesgaste': 1.0, 'gaiola': '21', 'forma': 'Oval'},
    {'luzPadrao': 1.32, 'profundidadeCanalPadrao': 6.80, 'alturaPadrao': 14.92, 'fatorDesgaste': 1.0, 'gaiola': '22', 'forma': 'Redondo'},
    {'luzPadrao': 0.00, 'profundidadeCanalPadrao': 0.00, 'alturaPadrao': 0.00, 'fatorDesgaste': 1.0, 'gaiola': 'DUMMY', 'forma': 'DUMMY'},
    {'luzPadrao': 0.00, 'profundidadeCanalPadrao': 0.00, 'alturaPadrao': 0.00, 'fatorDesgaste': 1.0, 'gaiola': 'DUMMY', 'forma': 'DUMMY'},
    {'luzPadrao': 0.00, 'profundidadeCanalPadrao': 0.00, 'alturaPadrao': 0.00, 'fatorDesgaste': 1.0, 'gaiola': 'DUMMY', 'DUMMY': 'DUMMY'},
    {'luzPadrao': 0.00, 'profundidadeCanalPadrao': 0.00, 'alturaPadrao': 0.00, 'fatorDesgaste': 1.0, 'gaiola': 'DUMMY', 'DUMMY': 'DUMMY'},
    {'luzPadrao': 0.00, 'profundidadeCanalPadrao': 0.00, 'alturaPadrao': 0.00, 'fatorDesgaste': 0.00, 'gaiola': 'DUMMY', 'DUMMY': 'DUMMY'},
    {'luzPadrao': 0.00, 'profundidadeCanalPadrao': 0.00, 'alturaPadrao': 0.00, 'fatorDesgaste': 0.00, 'gaiola': 'DUMMY', 'DUMMY': 'DUMMY'},
    ],
  };
  
}
